# Generated by Django 3.2.4 on 2021-07-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorofferslots',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 9, 56, 39, 384194)),
        ),
        migrations.AlterField(
            model_name='tutorofferslots',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 9, 56, 39, 384194)),
        ),
    ]
