# Generated by Django 3.2.5 on 2021-07-14 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtor_app', '0002_auto_20210709_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorofferslots',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 22, 2, 45, 978921)),
        ),
        migrations.AlterField(
            model_name='tutorofferslots',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 22, 2, 45, 978904)),
        ),
    ]
