# Generated by Django 3.2.5 on 2021-07-16 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtor_app', '0003_auto_20210714_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
        migrations.AlterField(
            model_name='tutorofferslots',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 0, 58, 6, 538919)),
        ),
        migrations.AlterField(
            model_name='tutorofferslots',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 0, 58, 6, 538901)),
        ),
    ]
